AV-5576: Replace zipruby gem with rubyzip
jobready/avetmiss_data pull request #20
Opened 2022-10-25 01:30 UTC by khanh227

2022-10-25 04:25 UTC, schlick requested changes
Just the one minor change please

2022-10-25 04:25 UTC, schlick commented on CHANGELOG.md
> +### Replace zipruby gem with rubyzip
Move this between Unreleased and 2.2.1. New entries go at the top of the list

2022-10-25 14:32 UTC, schlick requested changes

2022-10-25 14:32 UTC, schlick commented on lib/avetmiss_data/package.rb
>      end
I played around with it and banged my head many times. I ended up with this:

```
    Zip::File.add_buffer do |archive|
      files_list.each_pair do |stores_name, file_name|
        lines = send(stores_name).map { |store| store.to_line }.join("\n")
        archive.get_output_stream("#{file_name}.txt") { |os| os.write lines }
      end
    end
```

2022-10-25 14:32 UTC, schlick commented on lib/avetmiss_data/zip_file.rb
>        if content.nil?
I also had to make this change:

```
-      if content.nil?
+      if content.blank?
```

2022-10-25 14:32 UTC, schlick commented on lib/avetmiss_data/package.rb
>      end
But I also had to change the line mentioned in the other comment for zip_file.rb and also these lines in package_spec.rb:

```
-        File.open(temp_file.path, 'wb:ASCII-8BIT') { |f| f << package.to_zip_file }
+        File.open(temp_file.path, 'wb:ASCII-8BIT') { |f| f << package.to_zip_file.string }
```
and
```
-        File.open(temp_file.path, 'wb:ASCII-8BIT') { |f| f << package.to_aggregate_zip_file }
+        File.open(temp_file.path, 'wb:ASCII-8BIT') { |f| f << package.to_aggregate_zip_file.string }
```

2022-10-25 14:32 UTC, schlick commented on lib/avetmiss_data/package.rb
>      end
But I don't know if this change actually does what it is meant to achieve. I'm not convinced the specs are totally covering it.

2022-10-26 07:47 UTC, khanh227 commented
Thank @schlick for your help to review and suggestion, spec case fixed at last changes. 
![image](https://user-images.githubusercontent.com/15766927/197965968-2b02a38c-a4be-448d-a7ed-6aeec1e5eded.png)

2022-10-26 10:55 UTC, schlick approved these changes

2022-10-26 10:55 UTC, merged